import Head from "next/head";
import { ReactSlick } from "@/components/ReactSlick";

const settings = {
  dots: true,
  infinite: true,
  speed: 500,
  slidesToShow: 4,
  slidesToScroll: 1,
  initialSlide: 0,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 1,
        infinite: true,
        dots: true,
      },
    },
    {
      breakpoint: 768,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 1,
        initialSlide: 0,
      },
    },
    {
      breakpoint: 480,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
      },
    },
  ],
};

const commonSlideStyle = {
  height: "200px",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  color: "white",
  fontSize: "24px",
  fontWeight: "bold",
  margin: "0 5px",
  borderRadius: "8px",
} as const;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main
          style={{
            height: "100dvh",
            padding: "20px",
            boxSizing: "border-box",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            overflow: "auto",
          }}
        >
          <h1>ReactSlick Carousel Example</h1>
          <div style={{ width: "100%", maxWidth: "800px", margin: "0 auto" }}>
            <ReactSlick {...settings}>
              <div>
                <div
                  style={{
                    ...commonSlideStyle,
                    background: "#ff6b6b",
                  }}
                >
                  Slide 1
                </div>
              </div>
              <div>
                <div
                  style={{
                    ...commonSlideStyle,
                    background: "#4ecdc4",
                  }}
                >
                  Slide 2
                </div>
              </div>
              <div>
                <div
                  style={{
                    ...commonSlideStyle,
                    background: "#45b7d1",
                  }}
                >
                  Slide 3
                </div>
              </div>
              <div>
                <div
                  style={{
                    ...commonSlideStyle,
                    background: "#f7b731",
                  }}
                >
                  Slide 4
                </div>
              </div>
              <div>
                <div
                  style={{
                    ...commonSlideStyle,
                    background: "#5f27cd",
                  }}
                >
                  Slide 5
                </div>
              </div>
              <div>
                <div
                  style={{
                    ...commonSlideStyle,
                    background: "#00d2d3",
                  }}
                >
                  Slide 6
                </div>
              </div>
            </ReactSlick>
          </div>
        </main>
      </div>
    </>
  );
}
